name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Build the application
        run: |
          go mod download
          go build -o gowebterm main.go

      - name: Archive built binary
        uses: actions/upload-artifact@v2
        with:
          name: gowebterm
          path: gowebterm

      - name: Create Release
        id: create_release
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          body: Initial release
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gowebterm
          asset_name: gowebterm
          asset_content_type: application/octet-stream
